'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CMCv.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alert_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alert_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArrowFirst_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowFirst_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArrowLast_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowLast_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArrowLeft_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowLeft_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArrowRight_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowRight_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EDIT_002_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDIT_002_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Error_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Error_002_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_002_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FailToLoad_001_24_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FailToLoad_001_24_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FitPage_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FitPage_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FitWidth_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FitWidth_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading_001_24_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_001_24_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFile_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFile_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property petronas_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("petronas_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Resize_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Resize_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeazteccode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeazteccode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodecodabar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodecodabar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodecode11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodecode11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodecode128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodecode128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodecode39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodecode39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodecode93() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodecode93", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodedatamatrix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodedatamatrix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeean13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeean13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeean8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeean8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodefourstate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodefourstate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeintelligentmail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeintelligentmail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeinterleaved2of5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeinterleaved2of5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodemaxicode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodemaxicode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodemicropdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodemicropdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodepdf417() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodepdf417", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeplanet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeplanet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodepostnet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodepostnet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeqrcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeqrcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcoderoyalmail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcoderoyalmail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_barcodeupca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_barcodeupca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_charactersettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_charactersettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartarea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartarea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartarea3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartarea3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartaxes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartaxes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartbar3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartbar3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartbelowaxistitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartbelowaxistitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartcolumn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartcolumn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartcolumn3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartcolumn3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartdatalabels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartdatalabels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartdatatable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartdatatable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartformat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartformat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartgridlinesmajorhor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartgridlinesmajorhor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartgridlinesmajorvert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartgridlinesmajorvert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartlayout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartlayout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartlegend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartlegend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartline3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartline3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartpie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartpie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartpie3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartpie3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_chartsetdatarelation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_chartsetdatarelation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_charttitlemain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_charttitlemain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_deletepagenumber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_deletepagenumber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_deletetable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_deletetable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_deletetablecell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_deletetablecell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_deletetablecol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_deletetablecol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_deletetablerow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_deletetablerow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_edithyperlink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_edithyperlink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_formlayoutltr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_formlayoutltr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_formlayoutrtl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_formlayoutrtl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_hfdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_hfdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_hyphenation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_hyphenation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_indentdecrease() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_indentdecrease", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_indentincrease() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_indentincrease", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_insertbookmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_insertbookmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_insertfile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_insertfile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_inserthyperlink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_inserthyperlink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_insertlinebreak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_insertlinebreak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_insertpagenumber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_insertpagenumber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_inserttablecolleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_inserttablecolleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_inserttablecolright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_inserttablecolright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_inserttablerowabove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_inserttablerowabove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_inserttablerowbelow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_inserttablerowbelow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_languagedetection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_languagedetection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_listdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_listdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergedatefield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergedatefield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergedeletefield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergedeletefield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergefieldproperties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergefieldproperties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergehighlightfields() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergehighlightfields", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergeiffield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergeiffield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergeincludetextfield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergeincludetextfield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergeinsertfield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergeinsertfield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergenextfield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergenextfield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergenextiffield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergenextiffield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergeshowfieldcodes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergeshowfieldcodes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mailmergeshowfieldtext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mailmergeshowfieldtext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_mergetablecells() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_mergetablecells", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_newpage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_newpage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pagebreak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pagebreak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pagecolumnstwo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pagecolumnstwo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pagedialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pagedialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pageframedialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pageframedialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pagenumberbottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pagenumberbottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pagenumbertop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pagenumbertop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pageviewnormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pageviewnormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_pageviewprint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_pageviewprint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_paragraphsettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_paragraphsettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_printpreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_printpreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_selecttable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_selecttable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_selecttablecell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_selecttablecell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_selecttablecol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_selecttablecol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_selecttablerow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_selecttablerow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_setlanguage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_setlanguage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_spelling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_spelling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_splittable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_splittable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_splittableabove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_splittableabove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_splittablebelow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_splittablebelow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_splittablecells() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_splittablecells", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_styledialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_styledialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_tabledialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_tabledialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_tablegridlines() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_tablegridlines", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_tabs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_tabs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_textframe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_textframe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TED_16_zoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TED_16_zoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextEditor_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextEditor_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ZoomIn_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomIn_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ZoomOut_001_24_FFFFFFFF_FF5423C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomOut_001_24_FFFFFFFF_FF5423C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
